# 
# ---- This stuff would be for if we were for real ready for production ----
# ---- Would need to change the nginx stuff + i think maybe vite.config.js (?) ----
# 
# --------------------------------------------------------------------
# Stage 1: Build with Vite
# --------------------------------------------------------------------
#FROM node AS builder
#RUN echo "The value of APP_ENVIRONMENT is: ${APP_ENVIRONMENT}"
#WORKDIR /app
#COPY . .
#RUN npm install --legacy-peer-deps
#RUN npm run build

# --------------------------------------------------------------------
# Stage 2: Serve with nginx
# --------------------------------------------------------------------
#FROM nginx:stable-alpine
#COPY --from=builder /app/dist /usr/share/nginx/html
#COPY nginx.conf /etc/nginx/conf.d/default.conf
#EXPOSE 80

# ====================================================================
# Still using Vite while in development
# ====================================================================
# Using "preview" here instead of "dev" might help with the crashing errors.
FROM node

RUN echo "The value of APP_ENVIRONMENT is: ${APP_ENVIRONMENT}"

WORKDIR /app
COPY . .

RUN npm install --legacy-peer-deps
RUN npm run build

# Might need to change the exposed port here to 4173 (preview uses that, dev uses 5173)
EXPOSE 5173
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0"]
