# Stage 1: Build with Vite
#FROM node:18 AS builder
#WORKDIR /app
#COPY . .
#RUN npm install
#RUN npm run build

# Stage 2: Serve with Nginx
#FROM nginx:stable
#COPY --from=builder /app/dist /usr/share/nginx/html
#COPY ../nginx/default.conf /etc/nginx/conf.d/default.conf

# --------------------------------------------------------------------
# Still using Vite while in development
# --------------------------------------------------------------------
FROM node

# --------------------------------------------------------------------
# Set environment variables
# --------------------------------------------------------------------

# Make it available as an env variable inside the container
ENV APP_ENVIRONMENT=${APP_ENVIRONMENT}
RUN echo "The value of APP_ENVIRONMENT is: ${APP_ENVIRONMENT}"


# --------------------------------------------------------------------
# 
# --------------------------------------------------------------------
WORKDIR /app
COPY . .
RUN npm install --legacy-peer-deps
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
