FROM python:3.11

# --------------------------------------------------------------------
# Set environment variables
# --------------------------------------------------------------------
# Accept build-time argument
ARG APP_ENVIRONMENT=sandbox

# Make it available as an env variable inside the container
ENV APP_ENVIRONMENT=${APP_ENVIRONMENT}
RUN echo "The value of APP_ENVIRONMENT is: ${APP_ENVIRONMENT}"

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    DEBIAN_FRONTEND=noninteractive

WORKDIR /app

# Set the timezone to UTC
RUN ln -sf /usr/share/zoneinfo/UTC /etc/localtime && echo "UTC" > /etc/timezone

# --------------------------------------------------------------------
# Install system packages
# --------------------------------------------------------------------
RUN apt-get update && apt-get install -y \
    cmake \
    g++ \
    libblas-dev \
    liblapack-dev \
    libffi-dev \
    libpython3-dev \
    pkg-config \
    build-essential \
    postgresql-client \
    portaudio19-dev \
    python3-pyaudio \
    libasound2-dev \
    openjdk-17-jre-headless

ENV JAVA_HOME = /usr/lib/jvm/java-17-openjdk-amd64 \
    PATH      = $JAVA_HOME/bin:$PATH


# --------------------------------------------------------------------
# Install Python dependencies
# --------------------------------------------------------------------
# Upgrade pip and tools
RUN pip install --upgrade pip setuptools wheel

# Copy requirements
COPY requirements-web.txt .

# Pre-build wheels to cache them (using PEP 517 if needed)
RUN pip wheel --wheel-dir=/wheels --no-cache-dir --use-pep517 --prefer-binary --timeout=120 --retries=10 \
    -r requirements-web.txt

# Install packages only from wheels
RUN pip install --no-index --find-links=/wheels -r requirements-web.txt

# --------------------------------------------------------------------
# Install python-llama-cpp if in deployment mode
# --------------------------------------------------------------------
RUN if [ "${APP_ENVIRONMENT}" = "deployment" ]; then \
    pip install llama-cpp-python \
        --timeout=120 --retries=10 \
        --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu121 ; \
    fi

# --------------------------------------------------------------------
# Copy project files
# --------------------------------------------------------------------
COPY . .
