# GPU Enabled
FROM nvidia/cuda

# --------------------------------------------------------------------
# Set environment variables
# --------------------------------------------------------------------
ENV APP_ENVIRONMENT="deployment" \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    DEBIAN_FRONTEND=noninteractive \
    JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64" \
    PATH="$JAVA_HOME/bin:$PATH"

# Set the timezone to UTC
RUN ln -sf /usr/share/zoneinfo/UTC /etc/localtime && echo "UTC" > /etc/timezone

# --------------------------------------------------------------------
# Install system packages & Python
# --------------------------------------------------------------------
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    python3 \
    python3-pip \
    g++ \
    libblas-dev \
    liblapack-dev \
    libffi-dev \
    libpython3-dev \
    pkg-config \
    postgresql-client \
    portaudio19-dev \
    python3-pyaudio \
    libasound2-dev \
    openjdk-17-jre-headless

# --------------------------------------------------------------------
# Install Python dependencies
# --------------------------------------------------------------------
# Upgrade pip and tools
RUN pip3 install --upgrade pip setuptools wheel

# Set the working directory & copy requirements
WORKDIR /app
COPY requirements-web.txt .

# Pre-build wheels to cache them (using PEP 517 if needed)
RUN pip3 wheel --wheel-dir=/wheels --no-cache-dir --use-pep517 --prefer-binary --timeout=120 --retries=10 \
    -r requirements-web.txt

# Install packages only from wheels
RUN pip3 install --no-index --find-links=/wheels -r requirements-web.txt

# --------------------------------------------------------------------
# Install python-llama-cpp if in deployment mode
# --------------------------------------------------------------------
RUN pip3 install llama-cpp-python \
        --timeout=120 --retries=10 \
        --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu121

# --------------------------------------------------------------------
# Copy project files
# --------------------------------------------------------------------
COPY . .
