# Generated by Django 3.2.25 on 2025-05-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_alter_goal_startday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='startDay',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
    ]
