# ====================================================================
# Nginx
# ====================================================================
FROM nginx:1.27-alpine

# Which .conf file to use
ARG CONF_FILE
RUN echo "Building with CONF_FILE=$CONF_FILE"

# Remove the default site just to make sure it doesn’t interfere
RUN rm /etc/nginx/conf.d/default.conf

# Copy the sandbox file (should this filename be pulled form an .env variable?)
COPY ${CONF_FILE} /etc/nginx/conf.d/default.conf

# Wait for the Certbot certification to finish
#COPY wait-for-certs.sh /wait-for-certs.sh
#RUN chmod +x /wait-for-certs.sh
#ENTRYPOINT ["/wait-for-certs.sh"]
