# Generated by Django 3.2.25 on 2025-04-22 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('plwd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='PLwD', serialize=False, to='auth.user')),
                ('caregiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primary_caregiver', to=settings.AUTH_USER_MODEL)),
                ('linkedUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings_user', serialize=False, to='dementia_chat.profile')),
                ('patientViewOverall', models.BooleanField(default=True)),
                ('patientCanSchedule', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_user', to='dementia_chat.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chatID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('scores', models.JSONField(blank=True, null=True)),
                ('avgScores', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('messages', models.JSONField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('topics', models.CharField(blank=True, max_length=100, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_plwd', to='dementia_chat.profile')),
            ],
        ),
    ]
