# Generated by Django 5.1.5 on 2025-02-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dementia_chat', '0001_initial'),
    ]

    operations = [
    ]
