# Generated by Django 3.2.25 on 2025-02-06 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dementia_chat', '0002_patients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
